ALTER TABLE "Cost"
ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'other',
ADD COLUMN IF NOT EXISTS "rateCents" INTEGER,
ADD COLUMN IF NOT EXISTS "quantityHours" DECIMAL(7, 2),
ADD COLUMN IF NOT EXISTS "fuelGallons" DECIMAL(7, 2),
ADD COLUMN IF NOT EXISTS "fuelPriceCents" INTEGER,
ADD COLUMN IF NOT EXISTS "amountCents" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "vendor" TEXT,
ADD COLUMN IF NOT EXISTS "notes" TEXT;

UPDATE "Cost"
SET "amountCents" = ROUND("amount" * 100)::INTEGER
WHERE ("amountCents" IS NULL OR "amountCents" = 0)
  AND "amount" IS NOT NULL;
