import { notFound } from "next/navigation";
import { prisma } from "@/app/lib/db";
import { getAppUrlFromEnv } from "@/app/lib/integrations/x";

export async function generateMetadata({ params }: { params: { token: string } }) {
  const token = params.token;
  const share = await prisma.flightShareLink.findFirst({
    where: { token, revokedAt: null },
    select: {
      token: true,
      flight: {
        select: {
          tailNumber: true,
          tailNumberSnapshot: true,
          origin: true,
          destination: true,
          startTime: true
        }
      }
    }
  });

  if (!share) {
    return { title: "Flight share" };
  }

  const appUrl = getAppUrlFromEnv() || "https://app.flighttraks.com";
  const title = `FlightTraks · ${(share.flight.tailNumberSnapshot ?? share.flight.tailNumber).trim()}`;
  const desc = `${share.flight.origin} → ${share.flight.destination ?? "TBD"} · ${share.flight.startTime.toISOString().slice(0, 10)}`;
  const image = `${appUrl}/api/share/flight/${share.token}/card.png`;

  return {
    title,
    description: desc,
    openGraph: {
      title,
      description: desc,
      images: [image]
    },
    twitter: {
      card: "summary_large_image",
      title,
      description: desc,
      images: [image]
    }
  };
}

export default async function FlightSharePage({ params }: { params: { token: string } }) {
  const share = await prisma.flightShareLink.findFirst({
    where: { token: params.token, revokedAt: null },
    select: {
      token: true,
      flight: {
        select: {
          tailNumber: true,
          tailNumberSnapshot: true,
          origin: true,
          destination: true,
          startTime: true,
          durationMinutes: true,
          distanceNm: true
        }
      }
    }
  });

  if (!share) notFound();

  const tail = (share.flight.tailNumberSnapshot ?? share.flight.tailNumber).trim();
  const route = `${share.flight.origin} → ${share.flight.destination ?? "TBD"}`;

  return (
    <div className="mx-auto max-w-3xl space-y-4 p-6">
      <div className="space-y-1">
        <h1 className="text-2xl font-semibold text-slate-900 dark:text-slate-100">
          {tail}
        </h1>
        <p className="text-sm text-slate-600 dark:text-slate-400">{route}</p>
      </div>

      {/* Lightweight page so X/Twitter crawler can fetch metadata + card image */}
      <div className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={`/api/share/flight/${share.token}/card.png`}
          alt="Shared flight card"
          className="w-full"
        />
      </div>

      <p className="text-xs text-slate-500 dark:text-slate-400">
        Generated by FlightTraks.
      </p>
    </div>
  );
}

